# Generated by Django 5.0.7 on 2024-07-25 15:01

import django.contrib.postgres.fields
import django.contrib.postgres.search
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Puzzle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('pieces', models.IntegerField()),
                ('status', models.IntegerField(choices=[(1, 'Active'), (2, 'Inactive')], default=1)),
                ('image_urls', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(max_length=1024), blank=True, default=list, size=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('deposit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('condition', models.CharField(choices=[('Новий', 'New'), ('Ідеальний', 'Ideal'), ('Дуже хороший', 'Very_good'), ('Хороший', 'Good'), ('Задовільний', 'Alright')])),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PuzzleAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.attribute')),
                ('puzzle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.puzzle')),
            ],
        ),
        migrations.AddField(
            model_name='puzzle',
            name='attributes',
            field=models.ManyToManyField(through='catalog.PuzzleAttribute', to='catalog.attribute'),
        ),
    ]
