version: "3.7"

services:
  base-dev: &base-dev
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: dev
    tty: true
    init: true
    stdin_open: true
    volumes:
      - ./puzzles:/app/puzzles
      - ./pyproject.toml:/app/pyproject.toml
      - ./pdm.lock:/app/pdm.lock
      - ./manage.py:/app/manage.py

  backend:
    <<: *base-dev
    restart: unless-stopped
    command:
      [
        "python",
        "-m",
        "uvicorn",
        "--host",
        "0.0.0.0",
        "--port",
        "8080",
        "--reload",
        "puzzles.asgi:application"
      ]
    ports:
      - "8080:8080"
    depends_on:
      - db

  backend-shell:
    <<: *base-dev
    restart: unless-stopped
    command: bash

  db:
    image: postgres:13
    restart: unless-stopped
    environment:
      POSTGRES_DB: puzzle_db
      POSTGRES_USER: puzzle_user
      POSTGRES_PASSWORD: puzzle_pass
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
