# Generated by Django 5.0.7 on 2024-07-27 11:23

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='puzzle',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='catalog_puz_search__0a5818_gin'),
        ),
    ]
