# Generated by Django 5.0.7 on 2025-05-28 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_cartitem_verification_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='verification_photo',
            field=models.URLField(default=None, max_length=1024, null=True),
        ),
    ]
