# Generated by Django 5.0.7 on 2024-07-31 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_remove_cart_token_cart_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='verification_photo',
            field=models.URLField(max_length=1024, null=True),
        ),
    ]
