# Generated by Django 5.0.7 on 2024-07-31 11:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0002_remove_cart_token_cart_session_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Reserved'), (2, 'Active'), (3, 'Returned'), (4, 'Cancelled')], default=1)),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_deposit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('rented_at', models.DateTimeField(auto_now_add=True)),
                ('rented_due_date', models.DateField()),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_type', models.IntegerField(choices=[(1, 'Np'), (2, 'Up'), (3, 'Pickup'), (4, 'Courier')])),
                ('address', models.TextField(blank=True, null=True)),
                ('cart', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rental', to='cart.cart')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
