# Generated by Django 5.0.7 on 2024-08-17 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_cartitem_verification_photo'),
        ('rental', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='cart',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rental', to='cart.cart'),
        ),
        migrations.DeleteModel(
            name='RentalItem',
        ),
    ]
