# Generated by Django 5.0.7 on 2025-05-28 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0002_rental_cart_delete_rentalitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='delivery_type',
            field=models.IntegerField(choices=[(1, 'Nova_poshta'), (2, 'Ukr_poshta'), (3, 'Pickup'), (4, 'Courier')]),
        ),
    ]
