# Generated by Django 5.0.7 on 2025-05-28 18:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0003_alter_rental_delivery_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Reserved'), (2, 'Active'), (3, 'Returned'), (4, 'Cancelled')], default=1),
        ),
        migrations.AlterField(
            model_name='rental',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rentals', to=settings.AUTH_USER_MODEL),
        ),
    ]
