# Generated by Django 5.0.7 on 2025-05-28 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0004_alter_rental_status_alter_rental_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='total_deposit',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='total_price',
        ),
        migrations.AddField(
            model_name='rental',
            name='verification_photo_url',
            field=models.URLField(blank=True, default=None, max_length=1024, null=True),
        ),
    ]
