# Generated by Django 5.0.7 on 2025-05-28 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0005_remove_rental_total_deposit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='verification_photo_url',
        ),
        migrations.CreateModel(
            name='VerificationPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, default=None, max_length=1024, null=True)),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_photos', to='rental.rental')),
            ],
        ),
    ]
